package com.jf.PetApp.core.domain;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.HexFormat;

/**
 * A one-time, time-limited credential for the forgot-password flow. Only the SHA-256 hash of
 * the actual token ever reaches persistence ({@code tokenHash}) — the raw value exists only
 * transiently, generated by {@code RequestPasswordResetUseCaseImpl} and emailed to the user,
 * never stored. {@link #hash(String)} is the single place that turns a raw token into what
 * gets stored/looked-up, so the use cases on both ends (request + reset) always hash the same
 * way.
 */
public record PasswordResetToken(
        Long id,
        Long userId,
        String tokenHash,
        Instant expiresAt,
        Instant usedAt,
        Instant createdAt
) {

    public boolean isValid(Instant now) {
        return usedAt == null && now.isBefore(expiresAt);
    }

    public static String hash(String rawToken) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hashed = digest.digest(rawToken.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hashed);
        } catch (NoSuchAlgorithmException e) {
            // SHA-256 is a JDK-mandatory algorithm (JCA standard names) — this is unreachable.
            throw new IllegalStateException(e);
        }
    }
}
