-- Mentor conversations: each user gets their own set of chat threads with the
-- AI mentor, persisted server-side (title, messages) so history survives
-- reinstalls and syncs across devices — replacing the old client-only
-- SharedPreferences cache, which used one hardcoded key shared by whoever
-- was last logged in on a device. Messages cascade-delete with their
-- conversation.
create table jf_mentor_conversations (
    id bigint generated by default as identity,
    user_id bigint not null,
    title varchar(255),
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint fk_mentor_conversations_user foreign key (user_id) references jf_users (user_id)
);
create index idx_mentor_conversations_user on jf_mentor_conversations (user_id, updated_at desc);

create table jf_mentor_messages (
    id bigint generated by default as identity,
    conversation_id bigint not null,
    role varchar(20) not null,
    content text not null,
    created_at timestamp not null,
    primary key (id),
    constraint fk_mentor_messages_conversation foreign key (conversation_id)
        references jf_mentor_conversations (id) on delete cascade
);
create index idx_mentor_messages_conversation on jf_mentor_messages (conversation_id, created_at);
