-- Server-side missions. Purely additive — no existing table or constraint is
-- touched, same low-risk pattern as V6's achievement_unlocks/activity_log.
--
-- Mission *definitions* (code, period, target, XP reward, and the
-- learning-only condition each one checks) are executable logic and live in
-- code (application/gamification/mission/MissionCatalog.java), mirroring how
-- achievement definitions live in AchievementCatalog.java while only the
-- real, per-user state is persisted here.
--
-- mission_completions stores one row per (user, mission, period) once that
-- period's instance is completed — e.g. (42, 'daily_complete_lesson',
-- '2026-08-19') or (42, 'weekly_complete_module', '2026-W34'). period_key
-- disambiguates repeat instances of the same recurring mission across
-- different days/weeks, so a new period naturally gets a fresh row instead
-- of overwriting history. The unique constraint is the idempotency guard,
-- same pattern as uq_xp_events_idempotency / uq_achievement_unlocks —
-- evaluating missions twice in the same period never re-grants XP.

create table mission_completions (
    id bigint generated by default as identity,
    user_id bigint not null,
    mission_code varchar(64) not null,
    period_key varchar(16) not null,
    xp_awarded integer not null,
    completed_at timestamp not null,
    primary key (id),
    constraint fk_mission_completions_user foreign key (user_id) references jf_users (user_id),
    constraint uq_mission_completions unique (user_id, mission_code, period_key)
);
