-- Tags a lesson with the portfolio indicator concept(s) it teaches (e.g. "pe", "dy",
-- "roe" -- matching petapp_mobile's IndicatorEducationCatalog ids), so the client can
-- show a "you just learned about X -- here's how it looks on this asset" contextual
-- callback on the asset-details screen once the lesson is completed. See
-- docs/ACADEMY_ENGINE.md's "Educational Portfolio Intelligence" section and
-- DECISION-029.
--
-- Same shape and reconciliation semantics as academy_module_prerequisites: a plain
-- generated identity primary key plus a unique constraint on the natural business
-- key, deleted-for-parent and reinserted by AcademyContentSeedRunner on every boot.
-- Not authored for most lessons -- only where a lesson genuinely teaches a concept
-- that also has a real indicator on the asset-details screen; never a blanket tag.
create table academy_lesson_portfolio_concepts (
    id         bigint generated by default as identity,
    lesson_id  varchar(64) not null,
    concept_id varchar(32) not null,
    primary key (id),
    constraint uq_academy_lesson_portfolio_concepts unique (lesson_id, concept_id),
    constraint fk_academy_lesson_portfolio_concepts_lesson
        foreign key (lesson_id) references learning_lessons (lesson_id) on delete cascade
);
