-- Backs the refresh-token flow (RefreshTokenUseCase / LogoutUseCase). Only a SHA-256 hash of
-- the token is ever stored — never the raw value — same reasoning as
-- jf_password_reset_tokens.token_hash and jf_users.password.
--
-- revoked_at is nullable and set on rotation/logout/theft-detection rather than deleting the
-- row: a revoked-but-still-present row is what lets replayed-old-token reuse be detected at
-- all (see RefreshTokenUseCaseImpl) — deleting it on rotation would throw away the exact
-- signal that catches a stolen refresh token being replayed after the legitimate client has
-- already rotated past it.
--
-- replaced_by_token_hash records the rotation chain (which new token superseded this one) —
-- informational/audit only, nothing currently queries by it.

create table jf_refresh_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    token_hash varchar(255) not null,
    expires_at timestamp not null,
    revoked_at timestamp,
    replaced_by_token_hash varchar(255),
    created_at timestamp not null,
    primary key (id),
    constraint fk_refresh_tokens_user foreign key (user_id) references jf_users (user_id)
);

-- Every lookup is by token_hash (RefreshTokenUseCase never queries by user_id directly except
-- for the theft-detection bulk-revoke).
create unique index uq_refresh_tokens_token_hash on jf_refresh_tokens (token_hash);
create index ix_refresh_tokens_user_id on jf_refresh_tokens (user_id);
