-- Baseline schema for the Pet Invest App.
--
-- Mirrors exactly what Hibernate would otherwise auto-generate from the JPA
-- entity mappings (UserJpaEntity, PetJpaEntity, FinanceJpaEntity,
-- InvestmentJpaEntity) — verified by exporting Hibernate's own DDL for both
-- the H2 (dev) and PostgreSQL (prod) dialects and reconciling the two into
-- one portable script (VARCHAR + CHECK instead of H2's native ENUM type,
-- since PostgreSQL has no equivalent). From this migration onward, Flyway —
-- not Hibernate — owns the schema; `spring.jpa.hibernate.ddl-auto` is
-- `validate` everywhere, so Hibernate only checks the mappings match what's
-- here and never creates or alters anything itself.

create table jf_users (
    user_id bigint generated by default as identity,
    username varchar(255),
    email varchar(255),
    password varchar(255),
    is_active boolean not null,
    has_answered_onboarding boolean,
    investor_profile varchar(255) check (investor_profile in ('GUARDIAN', 'TACTICIAN', 'ADVENTURER')),
    preferred_language varchar(255),
    role varchar(255) check (role in ('ADMIN', 'USER')),
    primary key (user_id)
);

create table jf_finances (
    id integer generated by default as identity,
    balance numeric(38,2),
    user_id bigint not null unique,
    primary key (id),
    constraint fk_finances_user foreign key (user_id) references jf_users (user_id)
);

create table jf_pets (
    id integer generated by default as identity,
    name varchar(255),
    health integer not null,
    specie varchar(255) check (specie in ('DOG', 'CAT', 'WOLF', 'FOX', 'BEAR', 'LION')),
    user_id bigint not null unique,
    primary key (id),
    constraint fk_pets_user foreign key (user_id) references jf_users (user_id)
);

create table jf_investments (
    id integer generated by default as identity,
    name varchar(255),
    quantity float(53),
    purchase_price float(53),
    purchase_date date,
    type varchar(255) check (type in ('STOCKS', 'FIXED_INCOME', 'REAL_ESTATE', 'CRYPTO', 'FUNDS', 'OTHERS')),
    user_id bigint not null,
    primary key (id),
    constraint fk_investments_user foreign key (user_id) references jf_users (user_id)
);
