-- Academy's simulated wallet — new "simulated_portfolio" bounded context.
-- Applies everywhere (dev H2 and prod Postgres), unqualified table names,
-- same two-step pattern V1/V20 already used in this codebase: create here,
-- move to a real Postgres schema in db/migration-postgres/V23 (H2 can't
-- ALTER TABLE across schemas — see DevSchemalessNamingStrategy). There is
-- no existing data to migrate: the Financial Lab never persisted money,
-- only XP (docs/BACKEND_MODULE_PLAN.md §2) — every row created by this
-- migration's tables starts out empty.
--
-- One portfolio per user (unique user_id) — "create a fictitious wallet" is
-- satisfied by lazily provisioning this row on first access rather than a
-- separate user-facing creation step; see GetOrCreateSimulatedPortfolioUseCaseImpl.
create table simulated_portfolios (
    id bigint generated by default as identity,
    user_id bigint not null,
    virtual_balance numeric(19,2) not null,
    initial_balance numeric(19,2) not null,
    currency varchar(3) not null,
    reset_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint fk_simulated_portfolios_user foreign key (user_id) references jf_users (user_id),
    constraint uq_simulated_portfolios_user unique (user_id)
);

-- One row per (portfolio, ticker) currently held — a sell that fully closes
-- a position deletes its row rather than leaving a zero-quantity one.
create table simulated_positions (
    id bigint generated by default as identity,
    portfolio_id bigint not null,
    ticker varchar(20) not null,
    quantity numeric(19,6) not null,
    average_price numeric(19,2) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint fk_simulated_positions_portfolio foreign key (portfolio_id) references simulated_portfolios (id),
    constraint uq_simulated_positions_portfolio_ticker unique (portfolio_id, ticker)
);

-- Append-only ledger of every simulated buy/sell — both the audit trail and
-- the source of the order-history view. client_order_id is always present
-- (client-supplied, or a server-generated UUID when the client didn't send
-- one — see PlaceSimulatedOrderUseCaseImpl) and unique per portfolio, so a
-- retried place-order request is idempotent: the same shape as xp_events'
-- (userId, eventType, sourceId) idempotency key, adapted to one portfolio's
-- own order stream. NOT NULL avoids needing a partial/filtered unique index,
-- which isn't portable between H2 and Postgres.
create table simulated_orders (
    id bigint generated by default as identity,
    portfolio_id bigint not null,
    ticker varchar(20) not null,
    side varchar(4) not null,
    quantity numeric(19,6) not null,
    price numeric(19,2) not null,
    executed_at timestamp not null,
    client_order_id varchar(100) not null,
    primary key (id),
    constraint fk_simulated_orders_portfolio foreign key (portfolio_id) references simulated_portfolios (id),
    constraint chk_simulated_orders_side check (side in ('BUY', 'SELL')),
    constraint uq_simulated_orders_portfolio_client_order_id unique (portfolio_id, client_order_id)
);

create index ix_simulated_positions_portfolio_id on simulated_positions (portfolio_id);
create index ix_simulated_orders_portfolio_id on simulated_orders (portfolio_id);
