-- Audit trail for real-portfolio sync attempts (B3 or any future
-- brokerage/custody provider) — recorded even when the attempt is
-- DISABLED (no legitimate provider integration configured today; see
-- RealPortfolioSyncPort/B3RealPortfolioSyncAdapter). Unqualified here
-- (applies to both H2 dev and Postgres prod); moved into the existing
-- real_portfolio Postgres schema in db/migration-postgres/V26.
--
-- idempotency_key is unique per (user_email, provider): retrying the same
-- logical sync request returns the already-logged outcome instead of
-- re-running it, the same idempotency shape as xp_events and
-- simulated_orders.
create table real_portfolio_sync_log (
    id bigint generated by default as identity,
    user_email varchar(255) not null,
    provider varchar(50) not null,
    idempotency_key varchar(100) not null,
    status varchar(20) not null,
    started_at timestamp not null,
    finished_at timestamp not null,
    message varchar(500),
    primary key (id),
    constraint chk_real_portfolio_sync_log_status check (status in ('DISABLED', 'COMPLETED', 'FAILED')),
    constraint uq_real_portfolio_sync_log_user_provider_key unique (user_email, provider, idempotency_key)
);

create index ix_real_portfolio_sync_log_user_email on real_portfolio_sync_log (user_email);
