-- Petrimonium Health: manual cash-flow, recurring commitments and credit cards.
--
-- The common migration deliberately creates unqualified tables so it runs on
-- both H2 (dev) and PostgreSQL. PostgreSQL moves them into the dedicated
-- `health` schema in V30, following the same V22/V23 pattern used by the
-- simulated portfolio. No Wallet table is reused: jf_finances belongs to the
-- real_portfolio bounded context and is not a cash-flow ledger.

create table health_profiles (
    user_id bigint not null,
    country_code varchar(2) not null,
    primary_currency varchar(3) not null,
    locale_tag varchar(5) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (user_id),
    constraint fk_health_profiles_user foreign key (user_id) references jf_users (user_id),
    constraint chk_health_profiles_country check (country_code in ('BR', 'PT')),
    constraint chk_health_profiles_currency check (primary_currency in ('BRL', 'EUR')),
    constraint chk_health_profiles_locale check (locale_tag in ('pt-BR', 'pt-PT')),
    constraint uq_health_profiles_user_currency unique (user_id, primary_currency)
);

create table health_accounts (
    id bigint generated by default as identity,
    user_id bigint not null,
    name varchar(100) not null,
    account_type varchar(20) not null,
    initial_balance numeric(19,2) not null,
    balance_reference_date date not null,
    currency varchar(3) not null,
    archived boolean not null default false,
    idempotency_key varchar(100) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint chk_health_accounts_type check (account_type in ('CHECKING', 'SAVINGS', 'CASH', 'OTHER')),
    constraint fk_health_accounts_profile_currency foreign key (user_id, currency)
        references health_profiles (user_id, primary_currency),
    constraint uq_health_accounts_user_key unique (user_id, idempotency_key),
    constraint uq_health_accounts_id_user_currency unique (id, user_id, currency)
);

create table health_recurrences (
    id bigint generated by default as identity,
    user_id bigint not null,
    account_id bigint not null,
    entry_type varchar(20) not null,
    amount numeric(19,2) not null,
    currency varchar(3) not null,
    description varchar(200) not null,
    category varchar(80),
    day_of_month integer not null,
    start_date date not null,
    end_date date,
    active boolean not null default true,
    idempotency_key varchar(100) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint chk_health_recurrences_type check (entry_type in ('INCOME', 'EXPENSE')),
    constraint chk_health_recurrences_amount check (amount > 0),
    constraint chk_health_recurrences_day check (day_of_month between 1 and 31),
    constraint chk_health_recurrences_dates check (end_date is null or end_date >= start_date),
    constraint fk_health_recurrences_account foreign key (account_id, user_id, currency)
        references health_accounts (id, user_id, currency),
    constraint uq_health_recurrences_user_key unique (user_id, idempotency_key)
);

create table health_cards (
    id bigint generated by default as identity,
    user_id bigint not null,
    name varchar(100) not null,
    currency varchar(3) not null,
    closing_day integer not null,
    due_day integer not null,
    archived boolean not null default false,
    idempotency_key varchar(100) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint chk_health_cards_closing_day check (closing_day between 1 and 31),
    constraint chk_health_cards_due_day check (due_day between 1 and 31),
    constraint fk_health_cards_profile_currency foreign key (user_id, currency)
        references health_profiles (user_id, primary_currency),
    constraint uq_health_cards_user_key unique (user_id, idempotency_key),
    constraint uq_health_cards_id_user_currency unique (id, user_id, currency)
);

create table health_card_invoices (
    id bigint generated by default as identity,
    user_id bigint not null,
    card_id bigint not null,
    currency varchar(3) not null,
    cycle_month date not null,
    closing_date date not null,
    due_date date not null,
    invoice_status varchar(20) not null,
    paid_at date,
    paid_transaction_id bigint,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint chk_health_invoices_status check (invoice_status in ('OPEN', 'PAID')),
    constraint fk_health_invoices_card foreign key (card_id, user_id, currency)
        references health_cards (id, user_id, currency),
    constraint uq_health_invoices_card_cycle unique (card_id, cycle_month),
    constraint uq_health_invoices_id_user_currency unique (id, user_id, currency)
);

create table health_card_purchases (
    id bigint generated by default as identity,
    user_id bigint not null,
    card_id bigint not null,
    total_amount numeric(19,2) not null,
    currency varchar(3) not null,
    description varchar(200) not null,
    category varchar(80),
    purchase_date date not null,
    installment_count integer not null,
    record_source varchar(20) not null,
    external_provider varchar(80),
    external_id varchar(150),
    idempotency_key varchar(100) not null,
    created_at timestamp not null,
    primary key (id),
    constraint chk_health_purchases_amount check (total_amount > 0),
    constraint chk_health_purchases_installments check (installment_count between 1 and 120),
    constraint chk_health_purchases_source check (record_source in ('MANUAL', 'IMPORTED')),
    constraint fk_health_purchases_card foreign key (card_id, user_id, currency)
        references health_cards (id, user_id, currency),
    constraint uq_health_purchases_user_key unique (user_id, idempotency_key),
    constraint uq_health_purchases_external unique (user_id, external_provider, external_id)
);

create table health_card_installments (
    id bigint generated by default as identity,
    user_id bigint not null,
    purchase_id bigint not null,
    invoice_id bigint not null,
    currency varchar(3) not null,
    installment_number integer not null,
    installment_count integer not null,
    amount numeric(19,2) not null,
    primary key (id),
    constraint chk_health_installments_number check (
        installment_number >= 1 and installment_number <= installment_count
    ),
    constraint chk_health_installments_amount check (amount > 0),
    constraint fk_health_installments_purchase foreign key (purchase_id)
        references health_card_purchases (id),
    constraint fk_health_installments_invoice foreign key (invoice_id, user_id, currency)
        references health_card_invoices (id, user_id, currency),
    constraint uq_health_installments_purchase_number unique (purchase_id, installment_number)
);

create table health_transfers (
    id bigint generated by default as identity,
    user_id bigint not null,
    from_account_id bigint not null,
    to_account_id bigint not null,
    amount numeric(19,2) not null,
    currency varchar(3) not null,
    transfer_date date not null,
    description varchar(200),
    idempotency_key varchar(100) not null,
    created_at timestamp not null,
    primary key (id),
    constraint chk_health_transfers_amount check (amount > 0),
    constraint chk_health_transfers_accounts check (from_account_id <> to_account_id),
    constraint fk_health_transfers_from foreign key (from_account_id, user_id, currency)
        references health_accounts (id, user_id, currency),
    constraint fk_health_transfers_to foreign key (to_account_id, user_id, currency)
        references health_accounts (id, user_id, currency),
    constraint uq_health_transfers_user_key unique (user_id, idempotency_key)
);

create table health_transactions (
    id bigint generated by default as identity,
    user_id bigint not null,
    account_id bigint not null,
    entry_type varchar(30) not null,
    entry_status varchar(20) not null,
    amount numeric(19,2) not null,
    currency varchar(3) not null,
    description varchar(200) not null,
    category varchar(80),
    transaction_date date not null,
    record_source varchar(20) not null,
    external_provider varchar(80),
    external_id varchar(150),
    idempotency_key varchar(100) not null,
    transfer_id bigint,
    recurrence_id bigint,
    recurrence_month date,
    invoice_id bigint,
    deleted_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    primary key (id),
    constraint chk_health_transactions_type check (
        entry_type in ('INCOME', 'EXPENSE', 'TRANSFER_IN', 'TRANSFER_OUT', 'INVOICE_PAYMENT')
    ),
    constraint chk_health_transactions_status check (entry_status in ('PLANNED', 'REALIZED')),
    constraint chk_health_transactions_amount check (amount > 0),
    constraint chk_health_transactions_source check (record_source in ('MANUAL', 'IMPORTED', 'SYSTEM')),
    constraint fk_health_transactions_account foreign key (account_id, user_id, currency)
        references health_accounts (id, user_id, currency),
    constraint fk_health_transactions_transfer foreign key (transfer_id)
        references health_transfers (id),
    constraint fk_health_transactions_recurrence foreign key (recurrence_id)
        references health_recurrences (id),
    constraint fk_health_transactions_invoice foreign key (invoice_id, user_id, currency)
        references health_card_invoices (id, user_id, currency),
    constraint uq_health_transactions_user_key unique (user_id, idempotency_key),
    constraint uq_health_transactions_external unique (user_id, external_provider, external_id),
    constraint uq_health_transactions_recurrence_month unique (recurrence_id, recurrence_month),
    constraint uq_health_transactions_transfer_type unique (transfer_id, entry_type),
    constraint uq_health_transactions_invoice_payment unique (invoice_id)
);

create index ix_health_accounts_user on health_accounts (user_id);
create index ix_health_transactions_user_date on health_transactions (user_id, transaction_date);
create index ix_health_transactions_account on health_transactions (account_id);
create index ix_health_recurrences_user on health_recurrences (user_id);
create index ix_health_cards_user on health_cards (user_id);
create index ix_health_invoices_card_due on health_card_invoices (card_id, due_date);
create index ix_health_installments_invoice on health_card_installments (invoice_id);

-- The invoice points back to its payment transaction, while that transaction
-- points to the invoice. Add this FK only after both tables exist.
alter table health_card_invoices add constraint fk_health_invoices_paid_transaction
    foreign key (paid_transaction_id) references health_transactions (id);
