-- V33 tied each pet to exactly one app (unique(user_id, app_context) on jf_pets
-- itself). That was one iteration too strict: a user may want the SAME pet
-- (same name/specie/history) to act in more than one app, and to relink it
-- later — e.g. "my Wallet dog Rex should also be my Health pet now". That
-- needs a pet to be linkable to several apps at once, and relinkable, which a
-- column on jf_pets itself cannot express.
--
-- jf_pet_app_links is the join: which pet answers for which app, per user.
-- unique(user_id, app_context) keeps the invariant that still matters — at
-- most one pet answers for a given (user, app) at a time — while a single
-- pet_id can appear in more than one row (linked to several apps).
create table jf_pet_app_links (
    id integer generated by default as identity,
    pet_id integer not null,
    user_id bigint not null,
    app_context varchar(20) not null,
    primary key (id),
    constraint fk_pet_app_links_pet foreign key (pet_id) references jf_pets (id),
    constraint fk_pet_app_links_user foreign key (user_id) references jf_users (user_id),
    constraint uq_pet_app_links_user_app unique (user_id, app_context)
);

insert into jf_pet_app_links (pet_id, user_id, app_context)
    select id, user_id, app_context from jf_pets;

alter table jf_pets drop constraint uq_pets_user_app;
alter table jf_pets drop column app_context;
