-- Learning (Academy) + Gamification (XP) foundation for Invest Game V2.
--
-- `learning_modules`/`learning_lessons` are a lightweight, server-owned
-- catalog of *which* lesson/module ids exist and how much XP each is worth —
-- not the lesson content itself (that stays in the Flutter app's static
-- `AcademyCatalog`). This is what lets the server validate a completion
-- request and refuse to trust a client-supplied XP amount.
--
-- `xp_events` is the auditable XP ledger described in the product docs:
-- total XP is always SUM(amount), never a single mutable counter. Its
-- unique constraint on (user_id, event_type, source_id) is the idempotency
-- guard — completing the same lesson twice (retry, double-tap, replay)
-- never grants XP twice.

create table learning_modules (
    module_id varchar(64) not null,
    xp_reward integer not null,
    module_order integer not null,
    lesson_count integer not null,
    primary key (module_id)
);

create table learning_lessons (
    lesson_id varchar(64) not null,
    module_id varchar(64) not null,
    xp_reward integer not null,
    lesson_order integer not null,
    primary key (lesson_id),
    constraint fk_learning_lessons_module foreign key (module_id) references learning_modules (module_id)
);

create table lesson_progress (
    id bigint generated by default as identity,
    user_id bigint not null,
    lesson_id varchar(64) not null,
    completed_at timestamp not null,
    primary key (id),
    constraint fk_lesson_progress_user foreign key (user_id) references jf_users (user_id),
    constraint uq_lesson_progress unique (user_id, lesson_id)
);

create table xp_events (
    id bigint generated by default as identity,
    user_id bigint not null,
    event_type varchar(32) not null check (event_type in ('LESSON_COMPLETED', 'MODULE_COMPLETED')),
    amount integer not null,
    source_id varchar(64) not null,
    created_at timestamp not null,
    primary key (id),
    constraint fk_xp_events_user foreign key (user_id) references jf_users (user_id),
    constraint uq_xp_events_idempotency unique (user_id, event_type, source_id)
);

-- Seed the "Fundamentos do Investidor" / investor_foundations module — the
-- only module with authored content today. Ids and XP values are copied
-- verbatim from petapp_mobile/lib/features/academy/domain/services/academy_catalog.dart
-- so client and server never drift. Module XP reward (100) matches the
-- "complete module" row in docs/FEATURES.md's XP table.
insert into learning_modules (module_id, xp_reward, module_order, lesson_count) values
    ('investor_foundations', 100, 1, 6);

insert into learning_lessons (lesson_id, module_id, xp_reward, lesson_order) values
    ('foundations_what_is_investing', 'investor_foundations', 20, 1),
    ('foundations_assets_liabilities', 'investor_foundations', 20, 2),
    ('foundations_inflation', 'investor_foundations', 20, 3),
    ('foundations_compound_interest', 'investor_foundations', 20, 4),
    ('foundations_risk_return', 'investor_foundations', 20, 5),
    ('foundations_diversification', 'investor_foundations', 20, 6);
