-- Real, server-persisted achievements and engagement-streak tracking.
-- Purely additive — no existing table or constraint is touched, so there's
-- no migration risk to the already-seeded xp_events/lesson_progress data.
--
-- achievement_unlocks: achievement *definitions* (id, XP reward, unlock
-- condition) are executable logic and live in code
-- (application/gamification/achievement/AchievementCatalog.java), mirroring
-- how lesson *content* lives in the Flutter app's AcademyCatalog while only
-- ids/xpReward are DB-seeded. This table stores only the real, per-user
-- unlock *state*. Its unique constraint is the idempotency guard, same
-- pattern as uq_lesson_progress / uq_xp_events_idempotency — evaluating
-- achievements twice never re-grants XP for one already unlocked.
--
-- activity_log: one row per user per day they were meaningfully active
-- (login or lesson completion — see LoginUseCaseImpl, CompleteLessonUseCaseImpl).
-- Streaks are always recomputed live from this table (StreakCalculator),
-- never a stored/cached counter, matching the rest of this schema's
-- "ledger, not mutable counter" philosophy.

create table achievement_unlocks (
    id bigint generated by default as identity,
    user_id bigint not null,
    achievement_code varchar(64) not null,
    xp_awarded integer not null,
    unlocked_at timestamp not null,
    primary key (id),
    constraint fk_achievement_unlocks_user foreign key (user_id) references jf_users (user_id),
    constraint uq_achievement_unlocks unique (user_id, achievement_code)
);

create table activity_log (
    id bigint generated by default as identity,
    user_id bigint not null,
    activity_date date not null,
    primary key (id),
    constraint fk_activity_log_user foreign key (user_id) references jf_users (user_id),
    constraint uq_activity_log unique (user_id, activity_date)
);
