-- Backs the real forgot-password flow (RequestPasswordResetUseCase /
-- ResetPasswordUseCase). Only a SHA-256 hash of the token is ever stored —
-- never the raw value — so a leaked row can't be used to reset an account,
-- the same reasoning that keeps jf_users.password hashed rather than plain.
--
-- used_at is nullable and set once on redemption rather than deleting the
-- row: keeping a record of spent tokens costs nothing and preserves an
-- audit trail, matching this schema's "ledger, don't destroy history"
-- philosophy elsewhere (xp_events, activity_log).

create table jf_password_reset_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    token_hash varchar(255) not null,
    expires_at timestamp not null,
    used_at timestamp,
    created_at timestamp not null,
    primary key (id),
    constraint fk_password_reset_tokens_user foreign key (user_id) references jf_users (user_id)
);

-- Every lookup is by token_hash (ResetPasswordUseCase never queries by user_id directly).
create unique index uq_password_reset_tokens_token_hash on jf_password_reset_tokens (token_hash);
